spring:
  datasource:
    username: root
    password: zero
    url: jdbc:mysql://localhost:3306/product_management
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true