spring:
  datasource:
    username: root
    password: zero
    url: jdbc:mysql://localhost:3306/transaction_demo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true