spring:
  datasource:
    username: root
    password: zero
    url: jdbc:mysql://localhost:3306/todo_management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

#  security:
#    user:
#      name: hemant
#      password: 12345
#      roles:
#        - "ADMIN, USER, MANAGER"
