spring:
  datasource:
    username: root
    password: zero
    url: jdbc:mysql://localhost:3306/products?userSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true